namespace MEB_ARHUD_Calibration
{
    partial class Form_EditOffset
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }


        private void InitializeComponent()
        {
            this.GroupBox_ID3 = new System.Windows.Forms.GroupBox();
            this.TextBox_ID3_X = new System.Windows.Forms.TextBox();
            this.TextBox_ID3_Y = new System.Windows.Forms.TextBox();
            this.Label_ID3_X = new System.Windows.Forms.Label();
            this.Label_ID3_Y = new System.Windows.Forms.Label();
            this.Button_SaveID3 = new System.Windows.Forms.Button();
            this.GroupBox_ID4X = new System.Windows.Forms.GroupBox();
            this.Button_SaveID4X = new System.Windows.Forms.Button();
            this.Label_ID4X_Y = new System.Windows.Forms.Label();
            this.Label_ID4X_X = new System.Windows.Forms.Label();
            this.TextBox_ID4X_Y = new System.Windows.Forms.TextBox();
            this.TextBox_ID4X_X = new System.Windows.Forms.TextBox();
            this.GroupBox_ID6X = new System.Windows.Forms.GroupBox();
            this.Button_SaveID6X = new System.Windows.Forms.Button();
            this.Label_ID6X_Y = new System.Windows.Forms.Label();
            this.Label_ID6X_X = new System.Windows.Forms.Label();
            this.TextBox_ID6X_Y = new System.Windows.Forms.TextBox();
            this.TextBox_ID6X_X = new System.Windows.Forms.TextBox();
            this.GroupBox_AUDI = new System.Windows.Forms.GroupBox();
            this.Button_SaveAUDI = new System.Windows.Forms.Button();
            this.Label_AUDI_Y = new System.Windows.Forms.Label();
            this.Label_AUDI_X = new System.Windows.Forms.Label();
            this.TextBox_AUDI_Y = new System.Windows.Forms.TextBox();
            this.TextBox_AUDI_X = new System.Windows.Forms.TextBox();
            this.GroupBox_ID3.SuspendLayout();
            this.GroupBox_ID4X.SuspendLayout();
            this.GroupBox_ID6X.SuspendLayout();
            this.GroupBox_AUDI.SuspendLayout();
            this.SuspendLayout();
            this.GroupBox_ID3.Controls.Add(this.Button_SaveID3);
            this.GroupBox_ID3.Controls.Add(this.Label_ID3_Y);
            this.GroupBox_ID3.Controls.Add(this.Label_ID3_X);
            this.GroupBox_ID3.Controls.Add(this.TextBox_ID3_Y);
            this.GroupBox_ID3.Controls.Add(this.TextBox_ID3_X);
            this.GroupBox_ID3.Location = new System.Drawing.Point(12, 12);
            this.GroupBox_ID3.Name = "GroupBox_ID3";
            this.GroupBox_ID3.Size = new System.Drawing.Size(160, 159);
            this.GroupBox_ID3.TabIndex = 0;
            this.GroupBox_ID3.TabStop = false;
            this.GroupBox_ID3.Text = "ID3";
            this.TextBox_ID3_X.Location = new System.Drawing.Point(46, 29);
            this.TextBox_ID3_X.Name = "TextBox_ID3_X";
            this.TextBox_ID3_X.Size = new System.Drawing.Size(80, 21);
            this.TextBox_ID3_X.TabIndex = 0;
            this.TextBox_ID3_X.Text = "0";
            this.TextBox_ID3_Y.Location = new System.Drawing.Point(46, 70);
            this.TextBox_ID3_Y.Name = "TextBox_ID3_Y";
            this.TextBox_ID3_Y.Size = new System.Drawing.Size(80, 21);
            this.TextBox_ID3_Y.TabIndex = 1;
            this.TextBox_ID3_Y.Text = "0";
            this.Label_ID3_X.AutoSize = true;
            this.Label_ID3_X.Location = new System.Drawing.Point(23, 32);
            this.Label_ID3_X.Name = "Label_ID3_X";
            this.Label_ID3_X.Size = new System.Drawing.Size(11, 12);
            this.Label_ID3_X.TabIndex = 2;
            this.Label_ID3_X.Text = "X";
            this.Label_ID3_Y.AutoSize = true;
            this.Label_ID3_Y.Location = new System.Drawing.Point(23, 73);
            this.Label_ID3_Y.Name = "Label_ID3_Y";
            this.Label_ID3_Y.Size = new System.Drawing.Size(11, 12);
            this.Label_ID3_Y.TabIndex = 3;
            this.Label_ID3_Y.Text = "Y";
            this.Button_SaveID3.Location = new System.Drawing.Point(46, 112);
            this.Button_SaveID3.Name = "Button_SaveID3";
            this.Button_SaveID3.Size = new System.Drawing.Size(75, 23);
            this.Button_SaveID3.TabIndex = 4;
            this.Button_SaveID3.Text = "保存";
            this.Button_SaveID3.UseVisualStyleBackColor = true;
            this.Button_SaveID3.Click += new System.EventHandler(this.Button_SaveID3_Click);
            this.GroupBox_ID4X.Controls.Add(this.Button_SaveID4X);
            this.GroupBox_ID4X.Controls.Add(this.Label_ID4X_Y);
            this.GroupBox_ID4X.Controls.Add(this.Label_ID4X_X);
            this.GroupBox_ID4X.Controls.Add(this.TextBox_ID4X_Y);
            this.GroupBox_ID4X.Controls.Add(this.TextBox_ID4X_X);
            this.GroupBox_ID4X.Location = new System.Drawing.Point(178, 12);
            this.GroupBox_ID4X.Name = "GroupBox_ID4X";
            this.GroupBox_ID4X.Size = new System.Drawing.Size(160, 159);
            this.GroupBox_ID4X.TabIndex = 5;
            this.GroupBox_ID4X.TabStop = false;
            this.GroupBox_ID4X.Text = "ID4X";
            this.Button_SaveID4X.Location = new System.Drawing.Point(46, 112);
            this.Button_SaveID4X.Name = "Button_SaveID4X";
            this.Button_SaveID4X.Size = new System.Drawing.Size(75, 23);
            this.Button_SaveID4X.TabIndex = 4;
            this.Button_SaveID4X.Text = "保存";
            this.Button_SaveID4X.UseVisualStyleBackColor = true;
            this.Button_SaveID4X.Click += new System.EventHandler(this.Button_SaveID4X_Click);
            this.Label_ID4X_Y.AutoSize = true;
            this.Label_ID4X_Y.Location = new System.Drawing.Point(23, 73);
            this.Label_ID4X_Y.Name = "Label_ID4X_Y";
            this.Label_ID4X_Y.Size = new System.Drawing.Size(11, 12);
            this.Label_ID4X_Y.TabIndex = 3;
            this.Label_ID4X_Y.Text = "Y";
            this.Label_ID4X_X.AutoSize = true;
            this.Label_ID4X_X.Location = new System.Drawing.Point(23, 32);
            this.Label_ID4X_X.Name = "Label_ID4X_X";
            this.Label_ID4X_X.Size = new System.Drawing.Size(11, 12);
            this.Label_ID4X_X.TabIndex = 2;
            this.Label_ID4X_X.Text = "X";
            this.TextBox_ID4X_Y.Location = new System.Drawing.Point(46, 70);
            this.TextBox_ID4X_Y.Name = "TextBox_ID4X_Y";
            this.TextBox_ID4X_Y.Size = new System.Drawing.Size(80, 21);
            this.TextBox_ID4X_Y.TabIndex = 1;
            this.TextBox_ID4X_Y.Text = "0";
            this.TextBox_ID4X_X.Location = new System.Drawing.Point(46, 29);
            this.TextBox_ID4X_X.Name = "TextBox_ID4X_X";
            this.TextBox_ID4X_X.Size = new System.Drawing.Size(80, 21);
            this.TextBox_ID4X_X.TabIndex = 0;
            this.TextBox_ID4X_X.Text = "0";
            this.GroupBox_ID6X.Controls.Add(this.Button_SaveID6X);
            this.GroupBox_ID6X.Controls.Add(this.Label_ID6X_Y);
            this.GroupBox_ID6X.Controls.Add(this.Label_ID6X_X);
            this.GroupBox_ID6X.Controls.Add(this.TextBox_ID6X_Y);
            this.GroupBox_ID6X.Controls.Add(this.TextBox_ID6X_X);
            this.GroupBox_ID6X.Location = new System.Drawing.Point(344, 12);
            this.GroupBox_ID6X.Name = "GroupBox_ID6X";
            this.GroupBox_ID6X.Size = new System.Drawing.Size(160, 159);
            this.GroupBox_ID6X.TabIndex = 6;
            this.GroupBox_ID6X.TabStop = false;
            this.GroupBox_ID6X.Text = "ID6X";
            this.Button_SaveID6X.Location = new System.Drawing.Point(46, 112);
            this.Button_SaveID6X.Name = "Button_SaveID6X";
            this.Button_SaveID6X.Size = new System.Drawing.Size(75, 23);
            this.Button_SaveID6X.TabIndex = 4;
            this.Button_SaveID6X.Text = "保存";
            this.Button_SaveID6X.UseVisualStyleBackColor = true;
            this.Button_SaveID6X.Click += new System.EventHandler(this.Button_SaveID6X_Click);
            this.Label_ID6X_Y.AutoSize = true;
            this.Label_ID6X_Y.Location = new System.Drawing.Point(23, 73);
            this.Label_ID6X_Y.Name = "Label_ID6X_Y";
            this.Label_ID6X_Y.Size = new System.Drawing.Size(11, 12);
            this.Label_ID6X_Y.TabIndex = 3;
            this.Label_ID6X_Y.Text = "Y";
            this.Label_ID6X_X.AutoSize = true;
            this.Label_ID6X_X.Location = new System.Drawing.Point(23, 32);
            this.Label_ID6X_X.Name = "Label_ID6X_X";
            this.Label_ID6X_X.Size = new System.Drawing.Size(11, 12);
            this.Label_ID6X_X.TabIndex = 2;
            this.Label_ID6X_X.Text = "X";
            this.TextBox_ID6X_Y.Location = new System.Drawing.Point(46, 70);
            this.TextBox_ID6X_Y.Name = "TextBox_ID6X_Y";
            this.TextBox_ID6X_Y.Size = new System.Drawing.Size(80, 21);
            this.TextBox_ID6X_Y.TabIndex = 1;
            this.TextBox_ID6X_Y.Text = "0";
            this.TextBox_ID6X_X.Location = new System.Drawing.Point(46, 29);
            this.TextBox_ID6X_X.Name = "TextBox_ID6X_X";
            this.TextBox_ID6X_X.Size = new System.Drawing.Size(80, 21);
            this.TextBox_ID6X_X.TabIndex = 0;
            this.TextBox_ID6X_X.Text = "0";
            this.GroupBox_AUDI.Controls.Add(this.Button_SaveAUDI);
            this.GroupBox_AUDI.Controls.Add(this.Label_AUDI_Y);
            this.GroupBox_AUDI.Controls.Add(this.Label_AUDI_X);
            this.GroupBox_AUDI.Controls.Add(this.TextBox_AUDI_Y);
            this.GroupBox_AUDI.Controls.Add(this.TextBox_AUDI_X);
            this.GroupBox_AUDI.Location = new System.Drawing.Point(510, 12);
            this.GroupBox_AUDI.Name = "GroupBox_AUDI";
            this.GroupBox_AUDI.Size = new System.Drawing.Size(160, 159);
            this.GroupBox_AUDI.TabIndex = 7;
            this.GroupBox_AUDI.TabStop = false;
            this.GroupBox_AUDI.Text = "AUDI";
            this.Button_SaveAUDI.Location = new System.Drawing.Point(46, 112);
            this.Button_SaveAUDI.Name = "Button_SaveAUDI";
            this.Button_SaveAUDI.Size = new System.Drawing.Size(75, 23);
            this.Button_SaveAUDI.TabIndex = 4;
            this.Button_SaveAUDI.Text = "保存";
            this.Button_SaveAUDI.UseVisualStyleBackColor = true;
            this.Button_SaveAUDI.Click += new System.EventHandler(this.Button_SaveAUDI_Click);
            this.Label_AUDI_Y.AutoSize = true;
            this.Label_AUDI_Y.Location = new System.Drawing.Point(23, 73);
            this.Label_AUDI_Y.Name = "Label_AUDI_Y";
            this.Label_AUDI_Y.Size = new System.Drawing.Size(11, 12);
            this.Label_AUDI_Y.TabIndex = 3;
            this.Label_AUDI_Y.Text = "Y";
            this.Label_AUDI_X.AutoSize = true;
            this.Label_AUDI_X.Location = new System.Drawing.Point(23, 32);
            this.Label_AUDI_X.Name = "Label_AUDI_X";
            this.Label_AUDI_X.Size = new System.Drawing.Size(11, 12);
            this.Label_AUDI_X.TabIndex = 2;
            this.Label_AUDI_X.Text = "X";
            this.TextBox_AUDI_Y.Location = new System.Drawing.Point(46, 70);
            this.TextBox_AUDI_Y.Name = "TextBox_AUDI_Y";
            this.TextBox_AUDI_Y.Size = new System.Drawing.Size(80, 21);
            this.TextBox_AUDI_Y.TabIndex = 1;
            this.TextBox_AUDI_Y.Text = "0";
            this.TextBox_AUDI_X.Location = new System.Drawing.Point(46, 29);
            this.TextBox_AUDI_X.Name = "TextBox_AUDI_X";
            this.TextBox_AUDI_X.Size = new System.Drawing.Size(80, 21);
            this.TextBox_AUDI_X.TabIndex = 0;
            this.TextBox_AUDI_X.Text = "0";
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(685, 182);
            this.Controls.Add(this.GroupBox_AUDI);
            this.Controls.Add(this.GroupBox_ID6X);
            this.Controls.Add(this.GroupBox_ID4X);
            this.Controls.Add(this.GroupBox_ID3);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.Name = "Form_EditOffset";
            this.Text = "Offset修改";
            this.GroupBox_ID3.ResumeLayout(false);
            this.GroupBox_ID3.PerformLayout();
            this.GroupBox_ID4X.ResumeLayout(false);
            this.GroupBox_ID4X.PerformLayout();
            this.GroupBox_ID6X.ResumeLayout(false);
            this.GroupBox_ID6X.PerformLayout();
            this.GroupBox_AUDI.ResumeLayout(false);
            this.GroupBox_AUDI.PerformLayout();
            this.ResumeLayout(false);

        }


        private System.Windows.Forms.GroupBox GroupBox_ID3;
        private System.Windows.Forms.Label Label_ID3_Y;
        private System.Windows.Forms.Label Label_ID3_X;
        private System.Windows.Forms.TextBox TextBox_ID3_Y;
        private System.Windows.Forms.TextBox TextBox_ID3_X;
        private System.Windows.Forms.Button Button_SaveID3;
        private System.Windows.Forms.GroupBox GroupBox_ID4X;
        private System.Windows.Forms.Button Button_SaveID4X;
        private System.Windows.Forms.Label Label_ID4X_Y;
        private System.Windows.Forms.Label Label_ID4X_X;
        private System.Windows.Forms.TextBox TextBox_ID4X_Y;
        private System.Windows.Forms.TextBox TextBox_ID4X_X;
        private System.Windows.Forms.GroupBox GroupBox_ID6X;
        private System.Windows.Forms.Button Button_SaveID6X;
        private System.Windows.Forms.Label Label_ID6X_Y;
        private System.Windows.Forms.Label Label_ID6X_X;
        private System.Windows.Forms.TextBox TextBox_ID6X_Y;
        private System.Windows.Forms.TextBox TextBox_ID6X_X;
        private System.Windows.Forms.GroupBox GroupBox_AUDI;
        private System.Windows.Forms.Button Button_SaveAUDI;
        private System.Windows.Forms.Label Label_AUDI_Y;
        private System.Windows.Forms.Label Label_AUDI_X;
        private System.Windows.Forms.TextBox TextBox_AUDI_Y;
        private System.Windows.Forms.TextBox TextBox_AUDI_X;
    }
}